"""Batch I / J / K integration tests. See tests/conftest.py for setup."""
from decimal import Decimal

from app.core import system_settings as ss
from app.models.batch import Batch, BatchStatus, QCStatus
from app.models.company import ApprovalStatus, Company
from app.models.md_classification import MineralGroup
from app.models.order import OrderStatus, RevealLog, SettlementFeeStatus
from app.models.quotation import QuotationStatus
from app.models.user import User
from app.schemas.quotation import QuotationRequest
from app.schemas.rfq import RFQRequest
from app.services import order_service, quotation_service, rfq_service
from tests.conftest import Client


def test_master_data_crud_toggle_delete(admin, db, uniq):
    code = f"TG{uniq}"
    r = admin.post("/admin/master-data/mineral-groups/new",
                   {"code": code.lower(), "name_en": "Test group", "name_ar": "مجموعة", "sort_order": "5", "is_active": "1"})
    assert r.status_code == 303 and "error" not in r.headers["location"]
    row = db.query(MineralGroup).filter_by(code=code).one()           # code upper-cased
    r = admin.post(f"/admin/master-data/mineral-groups/{row.id}/edit",
                   {"code": code, "name_en": "Renamed", "sort_order": "5", "is_active": "1"})
    assert r.status_code == 303
    db.expire_all()
    assert db.get(MineralGroup, row.id).name_en == "Renamed"
    admin.post(f"/admin/master-data/mineral-groups/{row.id}/toggle")
    db.expire_all()
    assert db.get(MineralGroup, row.id).is_active is False
    r = admin.post(f"/admin/master-data/mineral-groups/{row.id}/delete")
    assert "msg=" in r.headers["location"]
    row_id = row.id
    db.expunge_all()
    assert db.query(MineralGroup).filter_by(id=row_id).first() is None


def test_delete_in_use_is_refused_with_message(admin, db):
    ind = db.query(MineralGroup).filter_by(code="IND").one()  
    r = admin.post(f"/admin/master-data/mineral-groups/{ind.id}/delete")
    assert "error=" in r.headers["location"] and "Deactivate" in __import__("urllib.parse").parse.unquote(r.headers["location"])
    db.expire_all()
    assert db.get(MineralGroup, ind.id) is not None


def test_validation_errors_rerender_form(admin):
    r = admin.post("/admin/master-data/mineral-types/new", {"code": "X1", "name_en": ""})
    assert r.status_code == 422 and "required" in r.text


def test_csv_export_import_roundtrip(admin, db, uniq):
    csv_text = f"code,name_en,name_ar,group_id,chemical_formula,sort_order,is_active,notes\nZZ{uniq},CSV mineral,,IND,XO2,9,true,\n"
    r = admin.post("/admin/master-data/mineral-types/import",
                   files={"file": ("types.csv", csv_text.encode(), "text/csv")})
    assert "created" in __import__("urllib.parse").parse.unquote(r.headers["location"])
    exported = admin.get("/admin/master-data/mineral-types/export.csv").text
    assert f"ZZ{uniq},CSV mineral" in exported and ",IND," in exported   # FK exported as code
    bad = "code,name_en,group_id\nQQ1,Bad,NOPE\n"
    r = admin.post("/admin/master-data/mineral-types/import", files={"file": ("b.csv", bad.encode(), "text/csv")})
    assert "not%20found" in r.headers["location"] or "not found" in __import__("urllib.parse").parse.unquote(r.headers["location"])


def test_product_code_autogenerated(admin, db):
    from app.models.md_classification import Grade, MineralType
    from app.models.md_product import ProductMaster
    from app.models.md_units import ParticleSize
    lim = db.query(MineralType).filter_by(code="LIM").one()
    g = db.query(Grade).filter_by(code="LIM-97").one()
    ps = db.query(ParticleSize).filter_by(code="PS-45UM").one()
    r = admin.post("/admin/master-data/product-masters/new", {
        "code": "", "name_en": "Auto code test", "product_type": "processed", "status": "active",
        "mineral_type_id": str(lim.id), "grade_id": str(g.id), "particle_size_id": str(ps.id), "currency": "SAR"})
    assert r.status_code == 303, r.text[:300]
    pm = db.query(ProductMaster).filter_by(name_en="Auto code test").order_by(ProductMaster.created_at.desc()).first()
    assert pm.code.startswith("MIN-CACO3-97-45UM")


def test_batch_qc_fail_rejects_and_blocks_release(admin, db):
    batch = db.query(Batch).filter_by(batch_number="LOT-2026-00125").one()
    # reset to quarantine and record an out-of-spec SiO2 value (spec ≤ 2 %)
    admin.post(f"/admin/batches/{batch.id}/status", {"status": "quarantine"})  # refused? only release is gated
    from app.models.md_quality import QualityParameter
    sio2 = db.query(QualityParameter).filter_by(code="SIO2").one()
    admin.post(f"/admin/batches/{batch.id}/results", {"parameter_id": str(sio2.id), "measured_value": "3.4"})
    db.expire_all()
    b = db.get(Batch, batch.id)
    assert b.qc_status == QCStatus.FAILED and b.status == BatchStatus.REJECTED
    r = admin.post(f"/admin/batches/{batch.id}/status", {"status": "released"})
    assert "error=" in r.headers["location"]
    # fix the value → passes again; with auto-release only QUARANTINE batches move, so re-quarantine first
    admin.post(f"/admin/batches/{batch.id}/status", {"status": "quarantine"})
    admin.post(f"/admin/batches/{batch.id}/results", {"parameter_id": str(sio2.id), "measured_value": "1.2"})
    db.expire_all()
    b = db.get(Batch, batch.id)
    assert b.qc_status == QCStatus.PASSED and b.status == BatchStatus.RELEASED

def _buyer_seller(db):
    buyer = db.query(User).filter_by(email="buyer@mineralstest.com").one()
    seller = db.query(User).filter_by(email="seller@mineralstest.com").one()
    return buyer, seller


def test_trade_flow_references_snapshot_reveal_and_fees(db):
    buyer, seller = _buyer_seller(db)
    rfq = rfq_service.create_rfq(db, buyer.company, RFQRequest(
        mineral_type="Limestone", quantity_value=Decimal("100"), quantity_unit="MT",
        delivery_location="Riyadh", delivery_timeframe="2 weeks"), created_by=buyer)
    assert rfq.rfq_reference and rfq.rfq_reference.startswith("RFQ-") and rfq.closes_at is not None
    q = quotation_service.submit_quotation(db, rfq, seller.company, QuotationRequest(
        price_value=Decimal("123.45"), lead_time_days=5), submitted_by=seller)
    assert q.quotation_reference.startswith("QUO-") and q.total_price == Decimal("12345.00") and q.valid_until
    order = order_service.accept_quotation(db, rfq, q, buyer.company)
    vat = Decimal(ss.get_setting(db, "vat_rate_pct"))
    assert order.order_reference.startswith("ORD-")
    assert order.subtotal_sar == Decimal("12345.00")
    assert order.vat_amount_sar == (Decimal("12345.00") * vat / 100).quantize(Decimal("0.01"))
    assert order.total_value_sar == order.subtotal_sar + order.vat_amount_sar
    assert order.identity_revealed_at is None
    order = order_service.confirm_order(db, order, confirmed_by=seller)
    assert order.identity_revealed_at is not None
    assert db.query(RevealLog).filter_by(order_id=order.id).count() == 1
    parties = {f.party: f for f in order.settlement_fees}
    assert set(parties) == {"buyer", "seller"}
    assert parties["buyer"].total_sar == parties["buyer"].amount_sar + parties["buyer"].vat_amount_sar


def test_competing_quotes_rejected_on_accept(db):
    from app.models.quotation import Quotation
    buyer, seller = _buyer_seller(db)
    rfq = rfq_service.create_rfq(db, buyer.company, RFQRequest(
        mineral_type="Silica", quantity_value=Decimal("10"), delivery_location="Jubail", delivery_timeframe="1 month"))
    q1 = quotation_service.submit_quotation(db, rfq, seller.company, QuotationRequest(price_value=Decimal("50"), lead_time_days=3))
    other_seller_company = db.query(Company).filter(Company.role == seller.company.role, Company.id != seller.company_id,
                                                    Company.status == ApprovalStatus.APPROVED).first()
    if other_seller_company is None:
        return  # seed has a single seller — nothing to compete
    q2 = quotation_service.submit_quotation(db, rfq, other_seller_company, QuotationRequest(price_value=Decimal("55"), lead_time_days=3))
    order_service.accept_quotation(db, rfq, q1, buyer.company)
    db.expire_all()
    assert db.get(Quotation, q2.id).status == QuotationStatus.REJECTED


def test_founding_member_fee_waiver(db, admin):
    buyer, seller = _buyer_seller(db)
    ss.set_setting(db, "waive_fees_founding_members", True)
    seller.company.is_founding_member = True
    db.commit()
    try:
        rfq = rfq_service.create_rfq(db, buyer.company, RFQRequest(
            mineral_type="Kaolin", quantity_value=Decimal("1"), delivery_location="Dammam", delivery_timeframe="now"))
        q = quotation_service.submit_quotation(db, rfq, seller.company, QuotationRequest(price_value=Decimal("10"), lead_time_days=1))
        order = order_service.confirm_order(db, order_service.accept_quotation(db, rfq, q, buyer.company))
        fees = {f.party: f.status for f in order.settlement_fees}
        assert fees["seller"] == SettlementFeeStatus.WAIVED
        assert fees["buyer"] == (SettlementFeeStatus.WAIVED if buyer.company.is_founding_member else SettlementFeeStatus.PENDING)
    finally:
        ss.set_setting(db, "waive_fees_founding_members", False)
        seller.company.is_founding_member = False
        db.commit()


def test_hidden_listing_not_browsable(db):
    from app.repositories import product_repository
    visible = product_repository.list_verified(db)
    if not visible:
        return
    p = visible[0]
    p.is_visible_to_buyers = False
    db.commit()
    try:
        assert product_repository.get_verified_by_id(db, p.id) is None
    finally:
        p.is_visible_to_buyers = True
        db.commit()

def test_system_settings_validation_and_save(admin, db):
    r = admin.post("/admin/system-settings", {"_category": "fees", "vat_rate_pct": "150", "lab_verification_fee_sar": "800",
                                               "settlement_fee_buyer_sar": "500", "settlement_fee_seller_sar": "500",
                                               "passport_fee_standard_sar": "0", "passport_fee_export_sar": "0"})
    assert "error=" in r.headers["location"]
    r = admin.post("/admin/system-settings", {"_category": "policy", "passport_validity_days": "400", "coa_validity_days": "0",
                                               "quotation_validity_days": "7", "rfq_open_days": "14", "qc_auto_release": "1"})
    assert "msg=" in r.headers["location"]
    db.expire_all()
    assert ss.get_setting(db, "passport_validity_days") == 400
    admin.post("/admin/system-settings/passport_validity_days/reset")
    db.expire_all()
    assert ss.get_setting(db, "passport_validity_days") == 365


def test_company_edit_vat_validation_and_suspend(admin, db):
    seller = db.query(User).filter_by(email="seller@mineralstest.com").one()
    c = seller.company
    base = {"company_name": c.company_name, "cr_number": c.cr_number, "license_or_accreditation_number": c.license_or_accreditation_number,
            "contact_email": c.contact_email, "subscription_tier": c.subscription_tier.value if c.subscription_tier else ""}
    r = admin.post(f"/admin/companies/{c.id}/edit", {**base, "vat_registration_number": "123"})
    assert "error=" in r.headers["location"]
    r = admin.post(f"/admin/companies/{c.id}/edit", {**base, "vat_registration_number": "300000000000003", "company_name_ar": "شركة"})
    assert "msg=" in r.headers["location"]
    r = admin.post(f"/admin/companies/{c.id}/status", {"status": "suspended", "reason": ""})
    assert "error=" in r.headers["location"]                      # reason required
    admin.post(f"/admin/companies/{c.id}/status", {"status": "suspended", "reason": "test"})
    db.expire_all()
    assert db.get(User, seller.id).is_active is False
    admin.post(f"/admin/companies/{c.id}/status", {"status": "approved"})
    db.expire_all()
    assert db.get(User, seller.id).is_active is True


def test_impersonation_gated_then_round_trip(admin, db):
    seller = db.query(User).filter_by(email="seller@mineralstest.com").one()
    ss.set_setting(db, "allow_impersonation", False); db.commit()
    r = admin.post(f"/admin/impersonate/{seller.id}")
    assert "error=" in r.headers["location"]
    ss.set_setting(db, "allow_impersonation", True); db.commit()
    try:
        r = admin.post(f"/admin/impersonate/{seller.id}")
        assert r.headers["location"].endswith("/home")
        assert admin.get("/seller/dashboard").status_code == 200    # now the seller
        assert admin.get("/admin/control-center").status_code == 403
        r = admin.post("/impersonation/stop")
        assert "/admin/control-center" in r.headers["location"]
        assert admin.get("/admin/control-center").status_code == 200
    finally:
        ss.set_setting(db, "allow_impersonation", False); db.commit()


def test_admin_order_override_and_fee_marking(admin, db):
    buyer, seller = _buyer_seller(db)
    rfq = rfq_service.create_rfq(db, buyer.company, RFQRequest(
        mineral_type="Dolomite", quantity_value=Decimal("2"), delivery_location="Riyadh", delivery_timeframe="asap"))
    q = quotation_service.submit_quotation(db, rfq, seller.company, QuotationRequest(price_value=Decimal("99"), lead_time_days=2))
    order = order_service.accept_quotation(db, rfq, q, buyer.company)
    r = admin.post(f"/admin/orders/{order.id}/status", {"status": "in_transit", "reason": ""})
    assert "error=" in r.headers["location"]
    admin.post(f"/admin/orders/{order.id}/status", {"status": "in_transit", "reason": "UAT"})
    db.expire_all()
    o = db.get(type(order), order.id)
    assert o.status == OrderStatus.IN_TRANSIT and o.identity_revealed_at is not None
    assert db.query(RevealLog).filter_by(order_id=o.id, triggered_by="admin").count() == 1
    fee = next(f for f in o.settlement_fees if f.party == "buyer")
    admin.post(f"/admin/finance/fees/{fee.id}", {"status": "paid", "reference": "MANUAL-1"})
    db.expire_all()
    assert db.get(type(fee), fee.id).status == SettlementFeeStatus.PAID


def test_admin_create_user_for_company(admin, db, uniq):
    seller = db.query(User).filter_by(email="seller@mineralstest.com").one()
    email = f"op{uniq.lower()}@mineralstest.com"
    r = admin.post("/admin/users/new", {"full_name": "Operator", "email": email, "password": "admin123",
                                        "role": "company", "company_id": str(seller.company_id), "company_role": "operator"})
    assert r.status_code == 303 and "error" not in r.headers["location"]
    u = db.query(User).filter_by(email=email).one()
    assert u.role == seller.role and u.company_role == "operator"
    assert Client(email).get("/seller/dashboard").status_code == 200


def test_enforce_admin_2fa_redirects(admin, db):
    ss.set_setting(db, "enforce_admin_2fa", True); db.commit()
    try:
        r = admin.get("/admin/control-center")
        assert r.status_code == 303 and "/my-profile/2fa/setup" in r.headers["location"]
    finally:
        ss.set_setting(db, "enforce_admin_2fa", False); db.commit()


def test_security_headers_and_private_documents(admin, db):
    r = admin.get("/admin/control-center")
    assert r.headers["X-Frame-Options"] == "DENY" and r.headers["X-Content-Type-Options"] == "nosniff"
    seller = db.query(User).filter_by(email="seller@mineralstest.com").one()
    assert admin.get(f"/admin/companies/{seller.company_id}/documents/cr").status_code in (200, 303)
    anon = Client()
    assert anon.get(f"/admin/companies/{seller.company_id}/documents/cr").status_code == 303   # → login


def test_document_magic_bytes_rejected():
    import pytest
    from app.services.document_upload_service import DocumentUploadError, validate_document

    class Fake:
        filename, content_type = "x.pdf", "application/pdf"
    with pytest.raises(DocumentUploadError):
        validate_document(Fake(), b"MZ\x90\x00 not a pdf", field_label="CR")
    assert validate_document(Fake(), b"%PDF-1.7 ok", field_label="CR") == "pdf"


def test_seller_listing_linked_to_catalog(db):
    from app.core import system_settings as ss
    from app.models.md_product import ProductMaster
    from app.models.product import Product
    pm = db.query(ProductMaster).filter_by(code="MIN-LIM-001").one()
    seller = Client("seller@mineralstest.com")
    base = {"mineral_type": "typed text", "quantity_value": "100", "quantity_unit": "MT", "price_currency": "SAR"}
    ss.set_setting(db, "require_catalog_product_on_listing", True); db.commit()
    try:
        r = seller.post("/seller/listings", base)
        assert r.status_code == 422 and "catalog product" in r.text
        r = seller.post("/seller/listings", {**base, "product_master_id": str(pm.id), "min_order_qty": "25"})
        assert r.status_code == 303
        pid = r.headers["location"].rstrip("/").split("/")[-1]
        p = db.get(Product, __import__("uuid").UUID(pid))
        assert p.product_master_id == pm.id and p.mineral_type == "Limestone" and p.name_en == pm.name_en
        assert p.min_order_qty == 25 and p.mine_source_id == pm.default_source_id
    finally:
        ss.set_setting(db, "require_catalog_product_on_listing", False); db.commit()


def test_subscription_limit_enforced_when_enabled(db):
    from app.core import system_settings as ss
    from app.models.md_commercial import SubscriptionPlan
    from app.services.rfq_service import RFQActionError
    buyer, _ = _buyer_seller(db)
    tier = buyer.company.subscription_tier
    if tier is None:
        return
    plan = db.query(SubscriptionPlan).filter_by(code=tier.value).one()
    old_limit = plan.max_active_rfqs
    plan.max_active_rfqs = 0
    ss.set_setting(db, "enforce_subscription_limits", True)
    db.commit()
    try:
        import pytest
        with pytest.raises(RFQActionError):
            rfq_service.create_rfq(db, buyer.company, RFQRequest(
                mineral_type="Any", quantity_value=Decimal("1"), delivery_location="x", delivery_timeframe="y"))
    finally:
        db.rollback()
        plan = db.query(SubscriptionPlan).filter_by(code=tier.value).one()
        plan.max_active_rfqs = old_limit
        ss.set_setting(db, "enforce_subscription_limits", False)
        db.commit()
